### ISSUE TITLE
example nodejs function do not work...

### ISSUE THREAD

**Issue by bondchan921** [aliyun/serverless-aliyun-function-compute#13]
example of read/write to table do not work....

```
'use strict';

var TableStore = require('tablestore');

var instanceName = 'xxxx';
var tableName = 'yyyy';

exports.handler = function(event, context, callback) {
  console.log('event: %s', event);

  var creds = context.credentials;
  var client = new TableStore.Client({
    accessKeyId: creds.accessKeyId,
    secretAccessKey: creds.accessKeySecret,
    stsToken: creds.securityToken,
    endpoint: 'http://'+instanceName+'.cn-hangzhou.ots-internal.aliyuncs.com',
    instancename: instanceName,
  });

  // put a row and get it immediately
  var putReq = {
    tableName: tableName,
    condition: new TableStore.Condition(TableStore.RowExistenceExpectation.IGNORE, null),
    primaryKey: [
      {'gid': 'hello'},
      {'uid': 'world'},
    ],
    attributeColumns: [
      {'col1': 'name'}, // string column
      {'col2': 100},    // integer column
    ],
  };

  client.putRow(putReq, function(err, data) {
    if (err) return callback(err);

    console.log('putRow suceess: %j', data);

    var getReq = {
      tableName: tableName,
      primaryKey: [
        {'gid': 'hello'},
        {'uid': 'world'},
      ],
      maxVersions: 2,
    };

    client.getRow(getReq, function(err, data) {
      if (err) return callback(err);

      console.log('getRow success: %j', data);

      callback(null, data);
    });
  });
};

```

Here is the error return ----> can't get anything valuable for further investigation, BTW I allow the access to the table to anyone.....

FC Invoke Start RequestId: 097a0383-f251-d8cd-7228-4a9855e60b15

2017-12-12T06:13:50.669Z 097a0383-f251-d8cd-7228-4a9855e60b15 [verbose] event: {

}

2017-12-12T06:13:50.680Z 097a0383-f251-d8cd-7228-4a9855e60b15 [error] {"errorMessage":"\n\u0016OTSInternalServerError\u0012\u0016Internal server error.","errorType":500,"stackTrace":["\u0016OTSInternalServerError\u0012\u0016Internal server error."]}

FC Invoke End RequestId: 097a0383-f251-d8cd-7228-4a9855e60b15

**Comment by bondchan921** [comment]
by configuring logProject and logStore at Service level, eventually shows do not have privilege to access table service

**Comment by joyeecheung** [comment]
The errors come from the OTS API and there isn't really much we can do about it at the moment.
