### ISSUE TITLE
Release nodejs8 support

### ISSUE THREAD

**Issue by mlev** [aliyun/serverless-aliyun-function-compute#27]
The examples list nodejs8 but when deploying with v1.2.0 the functions are always deployed with nodejs6 runtime.

It looks like some changes have been made to support nodejs8 (https://github.com/aliyun/serverless-aliyun-function-compute/pull/22/commits/cfdd9aa8438d7a938050e21814a9fc0e6ba03ddf) but they haven't been released to npm.

**Comment by JacksonTian** [comment]
The commit was released with 1.2.1.
