### ISSUE TITLE
Does function compute support Node v10/v12?

### ISSUE THREAD

**Issue by chenrui333** [aliyun/serverless-aliyun-function-compute#51]
Just curious, the last update on the doc was Last Nov, and Node v8 has EOL last December.

**Comment by lhr0909** [comment]
It should support `nodejsv12` - https://www.alibabacloud.com/help/zh/doc-detail/58011.htm

**Comment by chenrui333** [comment]
ok, last I checked it did not, seems got updated this time. Glad to see it.

Thanks for the follow up on this :)
