### ISSUE TITLE
TODOs

### ISSUE THREAD

**Issue by joyeecheung** [aliyun/serverless-aliyun-function-compute#6]
### Stronger validation

* [ ] Verify properties of supported events
* [ ] Verify provider configurations

### Update existing resources

* [ ] Update roles and policies after diffing their statements
* [ ] Update service configurations when necessary

### Features

* [ ] Support `serverless config credentials`
* [ ] Support `--package` option of `package` and `deploy`
* [ ] Local debugging (event simulation)
* [ ] Support ROS resource templates

### Make the CRUD of resources more robust

* [ ] Handle partial failures of batch operations
* [ ] Handle pagination of listing APIs
* [ ] Handle the delay of resource creation (esp. LogHub resources)

### Documentation

* [x] List services that need to be activated before using this plugin
* [x] Describe how to configure the RAM properly
* [x] Submit PR to upstream adding provider documentation

**Comment by ChenLi0830** [comment]
This is awesome, please keep up with the good work!

**Comment by bondchan921** [comment]
it's very good, I got java function deployed by commenting out the handler validation

```
  if (!/^[^.]+\.[^.]+$/.test(funcObject.handler)) {
        const errorMessage = [
          `The "handler" property for the function "${funcKey}" is invalid.`,
          ' Handlers should be specified like ${fileName}.${funcName}',
          ' Please check the docs for more info.',
        ].join('');
        throw new Error(errorMessage);
      }
```
